#!/usr/bin/env python3
"""Generate a Markdown vulnerability intelligence report."""

import argparse
import json
import subprocess
import sys
from datetime import datetime


def get_vulns(tech_name: str, limit: int = 15) -> list[dict]:
    """Run search_vulns.py and parse JSON output."""
    script = __file__.replace("generate_report.py", "search_vulns.py")
    result = subprocess.run(
        ["python", script, tech_name, "--limit", str(limit), "--json"],
        capture_output=True, text=True, timeout=30
    )
    if result.returncode != 0:
        print(f"Search failed: {result.stderr}", file=sys.stderr)
        return []
    return json.loads(result.stdout)


def group_by_severity(vulns: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": [], "UNKNOWN": []}
    for v in vulns:
        sev = v.get("severity", "UNKNOWN").upper()
        if sev not in groups:
            sev = "UNKNOWN"
        groups[sev].append(v)
    return groups


def generate_report(tech_name: str, vulns: list[dict]) -> str:
    groups = group_by_severity(vulns)
    total = len(vulns)
    critical_count = len(groups["CRITICAL"])
    high_count = len(groups["HIGH"])
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = []
    lines.append(f"# Vulnerability Intelligence Report: {tech_name}")
    lines.append(f"")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Total vulnerabilities:** {total} (Critical: {critical_count}, High: {high_count})")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    if total == 0:
        lines.append(f"> No vulnerabilities found for **{tech_name}**. This does not guarantee security — always follow security best practices.")
        return "\n".join(lines)

    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        if groups[sev]:
            lines.append(f"| {sev} | {len(groups[sev])} |")
    lines.append(f"")

    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        if not groups[sev]:
            continue
        lines.append(f"## {sev} Severity")
        lines.append(f"")
        for v in groups[sev]:
            cve = v.get("cve_id") or v.get("ghsa_id", "N/A")
            cvss = f"CVSS {v['cvss_score']}" if v.get("cvss_score") else "CVSS N/A"
            pkg = v.get("affected_package") or "N/A"
            patched = v.get("patched_version") or "No fix available"

            lines.append(f"### [{cve}] {v['title'][:80]}")
            lines.append(f"")
            lines.append(f"- **Package:** {pkg} ({v.get('ecosystem', 'N/A')})")
            lines.append(f"- **Severity:** {sev} | {cvss}")
            lines.append(f"- **Affected:** {v.get('vulnerable_range') or 'N/A'}")
            lines.append(f"- **Fixed in:** {patched}")
            lines.append(f"- **URL:** {v['url']}")
            lines.append(f"- **Published:** {v.get('published_at', 'N/A')}")
            lines.append(f"")
            if v.get("description"):
                lines.append(f"{v['description'][:300]}...")
            lines.append(f"")
        lines.append(f"")

    lines.append(f"---")
    lines.append(f"*Report generated by Vuln Explorer — AI Vulnerability Intelligence*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate vulnerability report for a tech stack")
    parser.add_argument("tech_name", help="Tech stack name (e.g. react, postgresql)")
    parser.add_argument("--limit", type=int, default=15, help="Max results (default: 15)")
    parser.add_argument("--output", help="Output file path (default: stdout)")

    args = parser.parse_args()

    print(f"Generating vulnerability report for: {args.tech_name}\n", file=sys.stderr)

    vulns = get_vulns(args.tech_name, args.limit)
    report = generate_report(args.tech_name, vulns)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"Report saved to: {args.output}", file=sys.stderr)
    else:
        print(report)


if __name__ == "__main__":
    main()
